apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
# type: Opaque
stringData:
  FTLCONF_webserver_api_password: YOUR_PIHOLE_ADMIN_PASSWORD # Replace with your actual password
