apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pihole
  name: pihole-etc-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/k8s-local/pihole/etc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - YOUR_NODE_NAME # example: k8s-node
