apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jellyfin-ns.yaml
  - jellyfin-deploy.yaml
  - jellyfin-pv.yaml
  - jellyfin-pvc.yaml
  - jellyfin-svc.yaml

namespace: jellyfin
